### ISSUE TITLE
Trailing comma in JSON causes console error

### ISSUE THREAD

**Issue by y-a-v-a** [simplyRoba/ImpExSupport#36]
## Expected Behavior
No console errors

## Actual Behavior
Console errors

## Steps to Reproduce the Problem

1. Open "Help" -> "Toggle Developer Tools"
1. Go to "Console" tab
1. See error

## Specifications
Due to the multi line comment entry being commented out in `language-configuration.json`, a trailing comma is present in the entry. This throws an error in the VS Code developer tools.

* Extension Version: ?
* VSCode Version: 1.24.0
* Platform: Mac OSX Sierra 10.12.6

![screen shot 2018-06-08 at 10 08 26](https://user-images.githubusercontent.com/375507/41146573-0dff4356-6b04-11e8-9744-4f81cd20f742.png)

**Comment by simplyRoba** [comment]
It does not break any functionality, a fast deployment is not necessary. Fix will be included in next maintenance release.
