### ISSUE TITLE
Trying to enable ColumnHighlighting and Visual Studio Code is saying it's an Unknown Configuration Setting

### ISSUE THREAD

**Issue by rpb138** [simplyRoba/ImpExSupport#9]
## Steps to Reproduce the Problem

1. Added ""impex.editor.columnHighlighting.enable": true" to User Settings Preference file
1. Green Underscore says 'impex.editor.columnHighlighting.enable' is an Unknown Configuration Setting
1. 

## Specifications

* Version: Code: Version 1.22.2 (1.22.2)
* Platform: MacOS Sierra 10.12.6
* Subsystem:

**Comment by simplyRoba** [comment]
It's `"impex.editor.columnHighlighting.enabled": true` the d at the end is missing. I fixed this in the docs.

If this does not help do the following:

Be sure the latest version of the extension is installed, for more info look [here](https://code.visualstudio.com/docs/editor/extension-gallery#_update-an-extension).

If this is done on Mac press `CMD + ,` to open the settings. A new tab should opened, where on the left side you see all default settings and on the right user settings and workspace settings. On the top is a search bar type `impex`. On the default side you should find now 
```
// Enables the column hoghlighting in impex files
  "impex.editor.columnHighlighting.enabled": false
```
copy this to the right side and and change it to true.

**Comment by simplyRoba** [comment]
no feedback .. closed
